 # Default value of indentation
defaultIndent: "  "


lookForAlignDelims:
    tabular:
      delims: 1
      alignDoubleBackSlash: 1
      spacesBeforeDoubleBackSlash: 1
      multiColumnGrouping: 0
      alignRowsWithoutMaxDelims: 1
      spacesBeforeAmpersand: 1
      spacesAfterAmpersand: 1
      justification: "left"
    tabularx:
      delims: 1
    longtable: 1
    tabu: 1
    array: 1
    matrix: 1
    bmatrix: 1
    Bmatrix: 1
    pmatrix: 1
    vmatrix: 1
    Vmatrix: 1
    align: 1
    align*: 1
    alignat: 1
    alignat*: 1
    aligned: 1
    cases: 1
    dcases: 1
    listabla: 1

indentAfterItems:
    itemize: 0
    enumerate: 0
    description: 0
    list: 0

